version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=impure
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=impure
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgres/data

volumes:
  db:
    driver: local
